---
title: "R Notebook"
output: html_notebook
---

##3.1: Shipments of Household Appliances

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
df <- read.csv(file = "./data/ApplianceSHipments.csv")

df$Quarter <- factor(df$Quarter, levels = c(
"Q1-1985",
"Q2-1985",
"Q3-1985",
"Q4-1985",
"Q1-1986",
"Q2-1986",
"Q3-1986",
"Q4-1986",
"Q1-1987",
"Q2-1987",
"Q3-1987",
"Q4-1987",
"Q1-1988",
"Q2-1988",
"Q3-1988",
"Q4-1988",
"Q1-1989",
"Q2-1989",
"Q3-1989",
"Q4-1989"))

df$Q <- c("Q1","Q2","Q3","Q4","Q1","Q2","Q3","Q4","Q1","Q2","Q3","Q4","Q1","Q2","Q3","Q4","Q1","Q2","Q3","Q4")

df$Year <- c("1985","1985","1985","1985","1986","1986","1986","1986","1987","1987","1987","1987","1988","1988","1988","1988","1989","1989","1989","1989")

df$Q <- factor(df$Q, levels=c("Q1","Q2","Q3","Q4"))
df$Year <- factor(df$Year)
```

```{r}
ggplot(df, aes(x=Quarter, y=Shipments, group=1)) + 
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggplot(df, aes(x=Quarter, y=Shipments, group=1)) + 
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(limits = c(3500, 5000))
```

```{r}
ggplot(df, aes(x=Year, y=Shipments, colour=Q, group=Q)) + 
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(limits = c(3500, 5000))
```

```{r}
df <- df %>%
  select(Shipments) %>%
  aggregate(by=list(Year=df$Year), FUN=sum)

ggplot(df, aes(x=Year, y=Shipments, group=1)) + 
  geom_line() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(limits = c(15000, 20000))
```
